### ISSUE TITLE
Integrate it with original lib?

### ISSUE THREAD

**Issue by SrBrahma** [WrathChaos/react-native-bouncy-checkbox-group#1]
Nice lib! But why don't adding it to the original lib? This one already required the another one as peer dep, and this code size is too small to be significant.

**Comment by WrathChaos** [comment]
Hello @SrBrahma,

The original library and this one's concepts and purposes are not the same. It's the basic principle from SOLID of `Separation of Concern`. Of course, they can be stuck in the same library but as I said their purposes are different so it's better to separate them.
