### ISSUE TITLE
isChecked first checkbox group

### ISSUE THREAD

**Issue by JoseDRD** [WrathChaos/react-native-bouncy-checkbox-group#12]
How can I set the first 'check' in checkbox group?

```
export const dataCheck = [
    {
        id: 0,
        text: 'first option',
        isChecked: true,
    },{
        id: 1,
        text: 'second option',
    },{
        id: 2,
        text: 'third option',
    }
]
```

The isChecked property for that doesn't work

**Comment by WrathChaos** [comment]
Hello @JoseDRD 
Can you try to use `initial` prop? 

Simply you can use `initial={0}` and it should check the first time as default
