### ISSUE TITLE
strikethrough problem!

### ISSUE THREAD

**Issue by durupanya** [WrathChaos/react-native-bouncy-checkbox-group#14]
![tempsnip](https://github.com/WrathChaos/react-native-bouncy-checkbox-group/assets/3500024/4e49e398-218b-4722-b7b1-c2a58289df31)

Hello, i'm using checkbox-group, when i check any item the item text strikethroug.
i coded  textDecorationLine: 'none' using props, you can see my code on attach image.

**Comment by WrathChaos** [comment]
Hello,

You should put that textStyle into the data so it can let you change each of the checkbox component. You can take a look at the example:
https://github.com/WrathChaos/react-native-bouncy-checkbox-group/blob/master/example/App.tsx
