### ISSUE TITLE
Type of id doesn't need to be number

### ISSUE THREAD

**Issue by ftzi** [WrathChaos/react-native-bouncy-checkbox-group#2]
https://github.com/WrathChaos/react-native-bouncy-checkbox-group/blob/ff0c2dfeb4a7939bfc66f4cb9e348b9ba32fd9ad/lib/BouncyCheckboxGroup.tsx#L15

keys may be strings!

**Comment by jacksonHendric** [comment]
Any progress on this? Id needs to be `string | number ` Should be an easy fix. 
Also why does onChange give me all properties of the radio button? It should just be id and text

**Comment by WrathChaos** [comment]
> Any progress on this? Id needs to be `string | number ` Should be an easy fix. Also why does onChange give me all properties of the radio button? It should just be id and text

Please check the PR comment :) I love to merge this but there are some issues. We can make it `string | number` but there are other issues as well

**Comment by WrathChaos** [comment]
[Version 0.1.1 is published with these changes](https://github.com/WrathChaos/react-native-bouncy-checkbox-group/releases/tag/0.1.1)
