### ISSUE TITLE
No margin between elements

### ISSUE THREAD

**Issue by SrBrahma** [WrathChaos/react-native-bouncy-checkbox-group#3]
Would be good to have a prop to set the style for each checkbox. Here is what I am having:

![image](https://user-images.githubusercontent.com/28177550/137278337-8fbb2342-4173-4f70-a661-ff214c966c33.png)

There is no horizontal nor vertical margin. There could be by default a leftMargin if index > 0. In this case I have flexWrap: 'wrap', but wouldn't be good to have verticalMargin by default, it would be better if I could add it by myself.

**Comment by WrathChaos** [comment]
Hello @SrBrahma,
You can set any style for each checkbox. 

Here is the documentation:
[Customization Optionals](https://github.com/WrathChaos/react-native-bouncy-checkbox-group#customization-optionals)

Also, you can check how I customize each one on the example project.

[Example](https://github.com/WrathChaos/react-native-bouncy-checkbox-group/tree/master/example)
