### ISSUE TITLE
Is it possible to set a default checked state for one option in a checkbox group?

### ISSUE THREAD

**Issue by dekrypto** [WrathChaos/react-native-bouncy-checkbox-group#5]

**Comment by ArturoTorresMartinez** [comment]
I was also looking for this, should we create a PR to add it to the documentation or has this been discussed somewhere else.

Just looking to assist! @dekrypto @WrathChaos

**Comment by WrathChaos** [comment]
If you want the PRs are always welcome @ArturoTorresMartinez  :) 

I will totally update the documentation, it is a bit low quality I guess :) 
It depends on the [react-native-bouncy-checkbox](https://github.com/WrathChaos/react-native-bouncy-checkbox) so its documentation is full however, I will move it to here as well.
