### ISSUE TITLE
isChecked doesn't work 

### ISSUE THREAD

**Issue by nartydev** [WrathChaos/react-native-bouncy-checkbox-group#6]
When we apply in data object isChecked item, the checkbox is not check

Here is my data structure: 
`  const data = [
    {
      id: 1,
      text: '...',
      isChecked: privateStatus,
      ...styles,
      onPress: (isChecked) => console.log(isChecked),
    },
    {
      id: 2,
      text: '...',
      isChecked: privateStatus,
      ...styles,
      onPress: (isChecked) => console.log(isChecked),
    },
    {
      id: 3,
      text: '...',
      ...styles,
      disabled: true,
      onPress: (isChecked) => console.log(isChecked),
    },
  ]`

Thank in advance

**Comment by WrathChaos** [comment]
Hello @nartydev,
Can you solve the issue?
