### ISSUE TITLE
Id needs to be string | number. Needs a value prop as well

### ISSUE THREAD

**Issue by jacksonHendric** [WrathChaos/react-native-bouncy-checkbox-group#9]
Hi, 

This issue was mentioned before but I don't understand why Id couldn't be `string | number.` 
If this is not possible there needs to be a value prop, so that we have `id, text, value `like any normal radio button component. 

I know I can just pass a value prop but the types keep throwing errors and I need to cast it to any for it to stop complaining. 

Thank you for the great work but I think this is an important fix.

**Comment by WrathChaos** [comment]
https://github.com/WrathChaos/react-native-bouncy-checkbox-group/releases/tag/0.1.1

**Comment by jacksonHendric** [comment]
Great thanks! Does this also include a `value` prop for the types?
